# A setup for the dir sorting

parentDir: C:\\Users\\$USERNAME\\
dir: Downloads
subcat:
  item1:
    name: pic
    extension:
    - gif
    - jpg
    - png
  item2:
    name: documents
    extension:
    - pdf
    - .doc
rename:
  rename1:
    old: 'copy'
    new: 'copy3'
  rename2:
    old: ' '
    new: ''